// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PromptTrails.Data;

#nullable disable

namespace PromptTrails.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704230508_SplitProblemSolutionEmbeddings")]
    partial class SplitProblemSolutionEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromptTrails.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.PromptEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssistantResponse")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("assistant_response");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("other")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Diff")
                        .HasColumnType("text")
                        .HasColumnName("diff");

                    b.Property<DateTimeOffset?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enriched_at");

                    b.PrimitiveCollection<List<string>>("FileExtensions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("file_extensions");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer")
                        .HasColumnName("files_changed");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("lines_added");

                    b.Property<int>("LinesRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("lines_removed");

                    b.Property<Vector>("ProblemEmbedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("problem_embedding");

                    b.Property<string>("ProblemEmbeddingText")
                        .HasColumnType("text")
                        .HasColumnName("problem_embedding_text");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<string>("PromptUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_uuid");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<Vector>("SolutionEmbedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("solution_embedding");

                    b.Property<string>("SolutionEmbeddingText")
                        .HasColumnType("text")
                        .HasColumnName("solution_embedding_text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_prompt_entries");

                    b.HasIndex("EnrichedAt")
                        .HasDatabaseName("ix_prompt_entries_enriched_at")
                        .HasFilter("enriched_at IS NULL");

                    b.HasIndex("ProblemEmbedding")
                        .HasDatabaseName("ix_prompt_entries_problem_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProblemEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProblemEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("PromptUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_entries_prompt_uuid");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_prompt_entries_session_id");

                    b.HasIndex("SolutionEmbedding")
                        .HasDatabaseName("ix_prompt_entries_solution_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SolutionEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SolutionEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("prompt_entries", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.PromptResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PromptEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("prompt_entry_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("ToolInput")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("tool_input");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolOutput")
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_output");

                    b.Property<string>("ToolUseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_use_id");

                    b.HasKey("Id")
                        .HasName("pk_prompt_responses");

                    b.HasIndex("PromptEntryId")
                        .HasDatabaseName("ix_prompt_responses_prompt_entry_id");

                    b.ToTable("prompt_responses", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_session_id");

                    b.Property<DateTimeOffset?>("CardAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("card_at");

                    b.Property<string>("ContextCard")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_card");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AgentSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_agent_session_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sessions_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GithubId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("github_id");

                    b.Property<string>("GithubLogin")
                        .HasColumnType("text")
                        .HasColumnName("github_login");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GithubId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_github_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.UserToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tokens_user_id");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PromptTrails.Models.Project", b =>
                {
                    b.HasOne("PromptTrails.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PromptTrails.Models.PromptEntry", b =>
                {
                    b.HasOne("PromptTrails.Models.Session", "Session")
                        .WithMany("Prompts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_entries_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PromptTrails.Models.PromptResponse", b =>
                {
                    b.HasOne("PromptTrails.Models.PromptEntry", "PromptEntry")
                        .WithMany("Responses")
                        .HasForeignKey("PromptEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_responses_prompt_entries_prompt_entry_id");

                    b.Navigation("PromptEntry");
                });

            modelBuilder.Entity("PromptTrails.Models.Session", b =>
                {
                    b.HasOne("PromptTrails.Models.Project", "Project")
                        .WithMany("Sessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_projects_project_id");

                    b.HasOne("PromptTrails.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptTrails.Models.UserToken", b =>
                {
                    b.HasOne("PromptTrails.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptTrails.Models.Project", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PromptTrails.Models.PromptEntry", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("PromptTrails.Models.Session", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("PromptTrails.Models.User", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
